import '../../domain/entities/job_detail.dart';

class JobDetailModel extends JobDetail {
  JobDetailModel({
    required super.id,
    required super.reference,
    required super.requestType,
    required super.customerName,
    required super.customerPhone,
    super.carLabel,
    required super.vehicleText,
    required super.appointmentDate,
    required super.startTime,
    required super.durationLabel,
    required super.addressText,
    super.dropAddressText,
    super.dropLatitude,
    super.dropLongitude,
    required super.estimatedFee,
    required super.quotedFee,
    required super.isPaid,
    super.paidAt,
    required super.status,
    required super.additionalCharges,
    required super.finalTotal,
    required super.balanceDue,
    super.balancePaid,
    super.balancePaidAt,
    super.actualHours,
    super.startOtpVerifiedAt,
    super.endOtpVerifiedAt,
  });

  factory JobDetailModel.fromJson(Map<String, dynamic> json) {
    // Use car_label as fallback if vehicle_text is null
    final vehicleText = json['vehicle_text'] ?? json['car_label'] ?? 'Unknown Vehicle';

    return JobDetailModel(
      id: json['id'].toString(),
      reference: json['reference'],
      requestType: json['request_type'],
      customerName: json['customer_name'],
      customerPhone: json['customer_phone'],
      carLabel: json['car_label'],
      vehicleText: vehicleText,
      appointmentDate: json['appointment_date'],
      startTime: json['start_time'],
      durationLabel: json['duration_label'] ?? '~1 hr',
      addressText: json['address_text'],
      dropAddressText: json['drop_address_text'],
      dropLatitude: (json['drop_latitude'] as num?)?.toDouble(),
      dropLongitude: (json['drop_longitude'] as num?)?.toDouble(),
      estimatedFee: (json['estimated_fee'] ?? '0').toString(),
      quotedFee: (json['quoted_fee'] ?? '0').toString(),
      isPaid: json['is_paid'] ?? false,
      paidAt: json['paid_at'],
      status: json['status'] ?? 'assigned',
      additionalCharges: (json['additional_charges'] ?? '0').toString(),
      finalTotal: (json['final_total'] ?? json['estimated_fee'] ?? '0').toString(),
      balanceDue: (json['balance_due'] ?? '0').toString(),
      balancePaid: json['balance_paid'] ?? false,
      balancePaidAt: json['balance_paid_at'],
      actualHours: (json['actual_hours'] as num?)?.toInt(),
      startOtpVerifiedAt: json['start_otp_verified_at'],
      endOtpVerifiedAt: json['end_otp_verified_at'],
    );
  }

  JobDetail toEntity() => JobDetail(
    id: id,
    reference: reference,
    requestType: requestType,
    customerName: customerName,
    customerPhone: customerPhone,
    carLabel: carLabel,
    vehicleText: vehicleText,
    appointmentDate: appointmentDate,
    startTime: startTime,
    durationLabel: durationLabel,
    addressText: addressText,
    dropAddressText: dropAddressText,
    dropLatitude: dropLatitude,
    dropLongitude: dropLongitude,
    estimatedFee: estimatedFee,
    quotedFee: quotedFee,
    isPaid: isPaid,
    paidAt: paidAt,
    status: status,
    additionalCharges: additionalCharges,
    finalTotal: finalTotal,
    balanceDue: balanceDue,
    balancePaid: balancePaid,
    balancePaidAt: balancePaidAt,
    actualHours: actualHours,
    startOtpVerifiedAt: startOtpVerifiedAt,
    endOtpVerifiedAt: endOtpVerifiedAt,
  );
}
